""" CONSTANT VARIABLES """
WINDOW_WIDTH = 300
WINDOW_HEIGHT = 300
PLATFORM_WIDTH = 60
PLATFORM_HEIGHT = 15
BALL_RADIUS = 7
BLOCK_SIZE = 10

""" NON-CONSTANT VARIABLES """
play = False
lost = False
score = 0
level = 0